version: "3"
services:
  app:
    build: .
    command: node build/src/main.js
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_FILE=${DATABASE_FILE}
      - BIRTHDAY_CHANNEL_ID=${BIRTHDAY_CHANNEL_ID}
    volumes:
      - ./data:/app/data/
    env_file: ./.env