version: "3"
services:
  app:
    build: .
    command: node build/main.js
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_FILE=${DATABASE_FILE}
      - BIRTHDAY_CHANNEL_ID=${BIRTHDAY_CHANNEL_ID}
    volumes:
      - ${DATABASE_FILE}:/app/${DATABASE_FILE}
    env_file: ./.env